apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx-server
  template:
    metadata:
      labels:
        app: my-nginx-server
    spec:
      containers:
      - name: my-nginx-server
        image: popesurprise/my-nginx-server:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-server
spec:
  type: LoadBalancer
  selector:
    app: my-nginx-server
  ports:
    - port: 80
      targetPort: 80
